name: build

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.compiler.cc }} build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      matrix:
        os:
          # - windows-latest
          - ubuntu-latest
          - macos-latest
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }

      fail-fast: false

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: Run git clone
        run: git clone https://github.com/JayXon/Leanify

      - name: Run make, print useful info, and set working dir
        id: make
        run: |
          cd Leanify
          ${{ matrix.compiler.cc }} --version
          make
          mv ./leanify ./leanify-${{ matrix.compiler.cc }}-${{ matrix.os }}
          echo "ASSET_PATH=${GITHUB_WORKSPACE}/Leanify/leanify-${{ matrix.compiler.cc }}-${{ matrix.os }}" >> $GITHUB_ENV

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          # prerelease: false
          title: "Development Build"
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
